---


- name: 必要パッケージインストール
  yum: name={{ item }}
  with_items:
  - nginx
  - httpd-tools

- name: nginxの有効化
  service: name=nginx enabled=yes state=started

- name: nginx.conf修正
  template: src=nginx_centos.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: restart nginx

- name: app定義
  template: src=nginx.j2 dest=/etc/nginx/conf.d/{{ rails.user }}.conf
  notify: restart nginx

- name: sslフォルダ作る
  file: path=/etc/nginx/ssl/{{ rails.nginx.domain }} mode=0755 state=directory recurse=yes

- name: 鍵コピー
  copy: src={{ item }} dest=/etc/nginx/ssl/{{ rails.nginx.domain }}/{{ item }} force=no
  notify: restart nginx
  with_items:
    - server.crt
    - server.key

- name: nginxが触れるようにパーミッション調整
  file: path=/home/{{ rails.user }} owner=logi group=logi mode=0755 state=directory
